get:
  tags:
    - "Account Settings"
  summary: "Fetch the current account settings"
  operationId: "getAccountSettings"

  responses:
    '200':
      description: "Account settings"
      schema:
        type: "object"
        properties:
          data:
            type: "object"
            properties:
              type:
                type: "string"
                enum: ["orders_redirect"]
              id:
                allOf:
                  - $ref: "#/definitions/UUID"
              attributes:
                $ref: "#/definitions/AccountSettings"

patch:
  tags:
    - "Account Settings"
  summary: "Update the account settings"
  operationId: "updateAccountSettings"
  parameters:
    - in: "body"
      name: "settings"
      description: "The settings to be updated"
      schema:
        type: "object"
        properties:
          data:
            type: "object"
            properties:
              type:
                type: "string"
                enum: ["account_settings"]
              id:
                description: "The current user id"
                allOf:
                  - $ref: "#/definitions/UUID"
              attributes:
                type: "object"
                properties:
                  first_name:
                    type: "string"
                  last_name:
                    type: "string"
                required:
                  - "first_name"
                  - "last_name"

  responses:
    '200':
      description: "Account settings"
      schema:
        type: "object"
        properties:
          data:
            type: "object"
            properties:
              type:
                type: "string"
                enum: ["orders_redirect"]
              id:
                allOf:
                  - $ref: "#/definitions/UUID"
              attributes:
                $ref: "#/definitions/AccountSettings"
