swagger: "2.0"
schemes:
  - https
host: utrust.com
basePath: /api
info:
  description: "JSON HTTP API for Merchants with an UTRUST user account."
  version: "1.0.0"
  title: "UTRUST Merchant API"
  contact:
    email: "apiteam@utrust.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  x-logo:
    url: "https://s2.coinmarketcap.com/static/img/coins/200x200/2320.png"
externalDocs:
  description: Check out the repo
  url: "https://github.com/utrustdev/merchant-api-spec"
produces:
  - application/json
consumes:
  - application/json

tags:
  - name: "order"

securityDefinitions:
  api_key: # security definition name (you can name it as you want)
    type: apiKey
    # The following options are specific to apiKey type
    in: header # Where API key will be passed: header or query
    name: api_key # API key paramteer name
  basic_auth: # security definition name (you can name it as you want)
    type: basic
