patch:
  tags:
    - Account Password
  summary: Update the account password
  operationId: updateAccountPassword
  parameters:
    - in: body
      name: account-password
      description: The password to be updated
      schema:
        type: object
        properties:
          data:
            type: object
            properties:
              type:
                type: string
                enum:
                  - password
              id:
                description: The current user id
                allOf:
                  - $ref: '#/definitions/UUID'
              attributes:
                type: object
                properties:
                  password:
                    type: string
                  new_password:
                    type: string
                  tfa_token:
                    type: string
                    description: Token is required if 2FA has been activated
                    example: '123456'
                required:
                  - password
                  - new_password
  responses:
    '200':
      description: Password updated
      schema:
        type: object
        properties:
          data:
            type: object
            properties:
              type:
                type: string
                enum:
                  - password
              id:
                allOf:
                  - $ref: '#/definitions/UUID'
              attributes:
                type: object
                properties:
                  message:
                    type: string
                    example: Password successfully changed.
